import unittest

class test__Exceptions(unittest.TestCase):
    def test_exception(self):
        pass

if __name__ == '__main__':
    unittest.main()
